apiVersion: skaffold/v1
kind: Config
deploy:
  kubectl:
    manifests:
      - ./config/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ashishkarki007/birdsquawk
      context: BirdSquawks-Service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: ashishkarki007/peep
      context: Peeps-Service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: ashishkarki007/query
      context: Query-Service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: ashishkarki007/birdsquawks-frontend
      context: birdsquawks-frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
